language: c
install:
  - wget https://raw.githubusercontent.com/ocaml/ocaml-ci-scripts/master/.travis-docker.sh
script: bash -ex .travis-docker.sh
services:
  - docker
env:
  global:
    - PINS="eqaf:."
    - DISTRO="debian-stable"
  matrix:
    - PACKAGE="eqaf" OCAML_VERSION=4.03.0 TESTS=true
    - PACKAGE="eqaf" OCAML_VERSION=4.04.2 TESTS=true
    - PACKAGE="eqaf" OCAML_VERSION=4.05.0 TESTS=true
    - PACKAGE="eqaf" OCAML_VERSION=4.06.0 TESTS=true
    - PACKAGE="eqaf" OCAML_VERSION=4.07.0 TESTS=true
